name: Docker Image CI

on:
  release:
    types: [ published ]
jobs:

  package: 
   runs-on: ubuntu-latest
   steps:
   - name: release-downloader
     uses: robinraju/release-downloader@v1.7
     with:
      latest: true
      fileName: "inspire-validator-2023.1.zip"
      
   
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
