name: Docker Image CI

on:
  release:
    types: [ published ]
jobs:

  package: 
   runs-on: ubuntu-latest
   steps:
    - name: Download Release Asset
      id: download_release_asset
      uses: i3h/download-release-asset@v1
      with:
        owner: manuelaromero-guadaltel
        repo: docs
        tag:  latest
        file: /inspire-validator-+[0-9]{4}[.][0-9]{1}+.zip/
        path: .
    - name: unzip
      id: unzip
      run: unzip *.zip
      
   
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker image
        uses: cloudposse/github-action-docker-build-push@1.9.0
        with:
          organization: 
          repository: 
          registry: ${{ steps.meta.outputs.tags }}
          image_name: ${{ steps.meta.outputs.labels }}
          login:
          password:
