name: Docker Image CI

on:
  release:
    types: [ published ]
jobs:

  package: 
   runs-on: ubuntu-latest
   steps:
    - name: Download Release Asset
      id: download_release_asset
      uses: i3h/download-release-asset@v1
      with:
        owner: manuelaromero-guadaltel
        repo: docs
        tag:  latest
        file: /inspire-validator-[0-9]{4}[.][0-9]{1}.zip/
        path: .
    - name: unzip
      id: unzip
      run: unzip *.zip
    - name: lista
      id: lista
      run: ls ./
      
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: manuelaromero/test001:latest
