# This is a basic workflow to help you get started with Actions

name: Release name

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  release:
    types: [ published ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Save Release name
        env:
          R_NAME: ${{ github.event.release.name }}
        run: |
          mkdir -p ./pr
          echo $R_NAME > ./r/r_name
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: r_name
          path: r/
      
